### ISSUE TITLE
Failing to get user ID and connection error on dendrite server

### ISSUE THREAD

**Issue by garret** [matrix-org/sliding-sync#318]
I think I am very close to get sliding sync working with the new version of dendrite (v0.13.3) that now supports the proxy more natively. However, after putting my username and password on Element X (on Android) and trying to log in, the Element X app stays stuck on the logging in screen. Looking at the sliding sync docker container logs, I see these (repeating) errors (I have redacted my real dendrite server address in the code below): 

```
[..]
21:05:42 INF Received connection from unknown access token, querying with homeserver
2023-09-30T21:05:42Z WRN failed to get user ID from device ID | error=Get "matrix.mydomain.com/_matrix/client/r0/account/whoami": unsupported protocol scheme ""
21:05:42 ERR failed to get or create Conn error="HTTP 502 : Get \"matrix.mydomain.com/_matrix/client/r0/account/whoami\": unsupported protocol scheme \"\""
[..]
```

I am running both dendrite and sliding sync on a Raspberry Pi 4 via docker. Both services are behind a Traefik reverse proxy. I have created two separate `A` records for dendrite and one for sliding sync. This is the `docker-compose` (did not include the databases containers for simplicity): 

```
  dendrite:
    user: ${PUID}:${PGID}
    image: matrixdotorg/dendrite-monolith
    container_name: dendrite
    volumes:
      - ${CONFIG_FOLDER}/dendrite/config:/etc/dendrite
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - dendrite-db
      - traefik
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dendrite-http.entrypoints=http"
      - "traefik.http.routers.dendrite-http.rule=Host(`${MATRIX_HOST}`)"
      - "traefik.http.routers.dendrite-http.middlewares=dendrite-https"
      - "traefik.http.middlewares.dendrite-https.redirectscheme.scheme=https"
      - "traefik.http.routers.dendrite-https.entrypoints=https"
      - "traefik.http.routers.dendrite-https.rule=Host(`${MATRIX_HOST}`)"
      - "traefik.http.routers.dendrite-https.tls.certresolver=ssl"
	  
  slidingsync:
    image: ghcr.io/matrix-org/sliding-sync
    container_name: slidingsync
    environment:
      - SYNCV3_SERVER=${MATRIX_HOST}
      - SYNCV3_SECRET=${SYNCV3_SECRET}
      - SYNCV3_BINDADDR=${SYNCV3_BINDADDR}
      - SYNCV3_DB=user=obscured dbname=obscured sslmode=disable host=obscured password=obscured
    depends_on:
      - slidingsync-db
      - traefik
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.slidingsync-http.entrypoints=http"
      - "traefik.http.routers.slidingsync-http.rule=Host(`${SLIDINGSYNC_HOST}`)"
      - "traefik.http.routers.slidingsync-http.middlewares=slidingsync-https"
      - "traefik.http.middlewares.slidingsync-https.redirectscheme.scheme=https"
      - "traefik.http.routers.slidingsync-https.entrypoints=https"
      - "traefik.http.routers.slidingsync-https.rule=Host(`${SLIDINGSYNC_HOST}`)"
      - "traefik.http.routers.slidingsync-https.tls.certresolver=ssl"
```

This is instead part of my `dendrite.yaml` (again, I've redacted the real domains): 

```
  # The server name to delegate server-server communications to, with optional port
  # e.g. localhost:443
  well_known_server_name: "https://matrix.mydomain.com"

  # The server name to delegate client-server communications to, with optional port
  # e.g. localhost:443
  well_known_client_name: "https://matrix.mydomain.com"

  # The server name to delegate sliding sync communications to, with optional port.
  # Requires `well_known_client_name` to also be configured.
  well_known_sliding_sync_proxy: "https://slidingsync.mydomain.com"
```

Before trying to access with Element X, sliding sync container does not show any errors in the logs: 

```
Sync v3 [0.99.10] (d214047)
Debug=false LogLevel= MaxConns=0
2023/09/30 20:51:56 goose: no migrations to run. current version: 20230822180807
20:51:57 INF creating handler
20:51:57 INF retrieved global snapshot from database
20:51:57 INF listening on :8008
20:51:57 INF StartV2Pollers num_devices=0 num_fail_decrypt=0
20:51:57 INF StartV2Pollers finished
```

It is without saying that I can log in without any issues with the "classic" Element on Android or Element-web to my dendrite server. 

**EDIT:** Tried to change `SYNCV3_SERVER=` variable from `matrix.mydomain.com` to `https://matrix.mydomain.com` but still get the same error. 

Just for completeness, this is the result of my `https://matrix.mydomain.com/.well-known/matrix/client`:

```
{"m.homeserver":{"base_url":"https://matrix.mydomain.com"},"org.matrix.msc3575.proxy":{"url":"https://slidingsync.mydomain.com"}}
```

**Comment by S7evinK** [comment]
As already mentioned in #dendrite:matrix.org: This, for some reason, sounds like the `slidingsync` service defined in your `docker-compose.yaml` didn't update the update after you changed to the correct `https://matrix.mydomain.com` or `http://dendrite:8008` (slightly better, for performance reasons).

```yaml
  slidingsync:
    image: ghcr.io/matrix-org/sliding-sync
    container_name: slidingsync
    environment:
      - SYNCV3_SERVER=http://dendrite:8008
      - SYNCV3_SECRET=${SYNCV3_SECRET}
      - SYNCV3_BINDADDR=${SYNCV3_BINDADDR}
      - SYNCV3_DB=user=obscured dbname=obscured sslmode=disable host=obscured password=obscured
```

and a `docker-compose up -d` (or `docker-compose down` + `docker-compose up -d`) should update the environment variable.

You can also inspect the currently running container using `docker inspect $NameOfSlidingSyncContaier` and look for `Config.Env`. (If you have `jq` installed -> `docker inspect $NameOfSlidingSyncContaier | jq '.[].Config.Env'`)
