### ISSUE TITLE
Missing Docker Compose?

### ISSUE THREAD

**Issue by melroy89** [matrix-org/sliding-sync#397]
I'm using Docker Compose v3 with Synapse (`matrixdotorg/synapse`) as well. 

I think it would be very valuable to provide an example docker compose for sliding sync Docker image. Allowing server admins to easily get sliding-sync up and running.

My idea is to just add an example compose yaml file to the git repo.

**Comment by Domoel** [comment]
I used this:

version: "3"

services:

  sliding-proxy:
    image: ghcr.io/matrix-org/sliding-sync:v0.99.1
    restart: unless-stopped
    ports:
      - "127.0.0.1:8881:8881"
    environment:
      - "SYNCV3_SECRET=<longrandomstring>"
      - "SYNCV3_SERVER=DOMAIN.ltd
      - "SYNCV3_DB=user=syncv3 dbname=syncv3 sslmode=disable host=sliding-postgres password=hunter2"
      - "SYNCV3_BINDADDR=0.0.0.0:8881"
    depends_on:
      - sliding-postgres
    networks: 
         ### Change to your matrix network
         - synapse_default

  sliding-postgres:
    image: docker.io/postgres:15-alpine
    restart: unless-stopped
    environment:
      - "POSTGRES_USER=syncv3"
      - "POSTGRES_PASSWORD=hunter2"
      - "POSTGRES_DB=syncv3"
    volumes:
      - /volume2/docker/slidingsync/sliding_db_data:/var/lib/postgresql/data
    networks: 
         ### Change to your matrix network
         - synapse_default

volumes:
  sliding_db_data:

networks:
   # Change to your matrix network
   synapse_default:
      external: true
      name: synapse_default

**Comment by melroy89** [comment]
You might want to add your example in a markdown code block.

Anyhow. I think such an example should be added to the git repo.

**Comment by vahtos** [comment]
I needed to convert the instructions to docker-compose too. Here's the formatted version of the above comment.
```
services:
  sliding-proxy:
    image: ghcr.io/matrix-org/sliding-sync:v0.99.1
    restart: unless-stopped
    ports:
      - "127.0.0.1:8881:8881"
    environment:
      - "SYNCV3_SECRET="
      - "SYNCV3_SERVER=DOMAIN.ltd
      - "SYNCV3_DB=user=syncv3 dbname=syncv3 sslmode=disable host=sliding-postgres password=hunter2"
      - "SYNCV3_BINDADDR=0.0.0.0:8881"
    depends_on:
       - sliding-postgres
    networks:
       - synapse_default

  sliding-postgres:
    image: docker.io/postgres:15-alpine
    restart: unless-stopped
    environment:
      - "POSTGRES_USER=syncv3"
      - "POSTGRES_PASSWORD=hunter2"
      - "POSTGRES_DB=syncv3"
    volumes:
      - /volume2/docker/slidingsync/sliding_db_data:/var/lib/postgresql/data
    networks:
      - synapse_default

volumes:
  sliding_db_data:

networks:
  synapse_default:
    external: true
    name: synapse_default
```
